dist: xenial   # required for Python >= 3.7

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
    - "pip install -r requirements.txt"
    - "pip install flask"
    - "pip install pytest-cov" #This plugin produces coverage reports
    - "pip install codecov" #install codecov

before_script:
  #

script:
  - pytest --cov-config=.coveragerc --cov-report term-missing --cov  # check test coverage with pytest-cov

after_script:

  # start the web app
  - |
    python app.py &
    APP_PID=$!

  - kill $APP_PID

env:
  #- CODECOV_TOKEN=<token>#IF ONLY YOU HAVE A PRIVATE REPOSITORY

after_success:
  # Generates coverage report, public repo using Travis:
  # Source: https://dev.to/j0nimost/using-codecov-with-travis-ci-pytest-cov-1dfj
  - codecov